# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arqonbus/proto/arqon.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'arqonbus/proto/arqon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61rqonbus/proto/arqon.proto\x12\x05\x61rqon\"Q\n\x07Triplet\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\";\n\tAssertion\x12\x0c\n\x04text\x18\x01 \x01(\t\x12 \n\x08triplets\x18\x02 \x03(\x0b\x32\x0e.arqon.Triplet\"#\n\x13\x43onsultationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x7f\n\x14\x43onsultationResponse\x12\'\n\x07verdict\x18\x01 \x01(\x0e\x32\x16.arqon.HolonomyVerdict\x12)\n\x11involved_triplets\x18\x02 \x03(\x0b\x32\x0e.arqon.Triplet\x12\x13\n\x0b\x65xplanation\x18\x03 \x01(\t\"\xd3\x01\n\nTruthGraph\x12%\n\x05nodes\x18\x01 \x03(\x0b\x32\x16.arqon.TruthGraph.Node\x12%\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x16.arqon.TruthGraph.Edge\x12\x0f\n\x07version\x18\x03 \x01(\x05\x1a.\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x1a\x36\n\x04\x45\x64ge\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x0e\n\x06parity\x18\x03 \x01(\x05\"T\n\x10IngestionRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x18\n\x10include_patterns\x18\x02 \x03(\t\x12\x18\n\x10\x65xclude_patterns\x18\x03 \x03(\t\"|\n\x0fIngestionStatus\x12\x14\n\x0c\x63urrent_file\x18\x01 \x01(\t\x12\x17\n\x0fprocessed_files\x18\x02 \x01(\x05\x12\x13\n\x0btotal_files\x18\x03 \x01(\x05\x12\x12\n\nfact_count\x18\x04 \x01(\x05\x12\x11\n\tcompleted\x18\x05 \x01(\x08*Y\n\x0fHolonomyVerdict\x12\x0e\n\nCONSISTENT\x10\x00\x12\x11\n\rCONTRADICTION\x10\x01\x12\x13\n\x0fNULL_HYPOTHESIS\x10\x02\x12\x0e\n\nTYPE_ERROR\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arqonbus.proto.arqon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOLONOMYVERDICT']._serialized_start=773
  _globals['_HOLONOMYVERDICT']._serialized_end=862
  _globals['_TRIPLET']._serialized_start=37
  _globals['_TRIPLET']._serialized_end=118
  _globals['_ASSERTION']._serialized_start=120
  _globals['_ASSERTION']._serialized_end=179
  _globals['_CONSULTATIONREQUEST']._serialized_start=181
  _globals['_CONSULTATIONREQUEST']._serialized_end=216
  _globals['_CONSULTATIONRESPONSE']._serialized_start=218
  _globals['_CONSULTATIONRESPONSE']._serialized_end=345
  _globals['_TRUTHGRAPH']._serialized_start=348
  _globals['_TRUTHGRAPH']._serialized_end=559
  _globals['_TRUTHGRAPH_NODE']._serialized_start=457
  _globals['_TRUTHGRAPH_NODE']._serialized_end=503
  _globals['_TRUTHGRAPH_EDGE']._serialized_start=505
  _globals['_TRUTHGRAPH_EDGE']._serialized_end=559
  _globals['_INGESTIONREQUEST']._serialized_start=561
  _globals['_INGESTIONREQUEST']._serialized_end=645
  _globals['_INGESTIONSTATUS']._serialized_start=647
  _globals['_INGESTIONSTATUS']._serialized_end=771
# @@protoc_insertion_point(module_scope)
