# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bus_payload.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'bus_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62us_payload.proto\x12\x0e\x61rqon.pybus.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe6\x02\n\nBusPayload\x12\x13\n\x0b\x65nvelope_id\x18\x01 \x01(\t\x12\x15\n\renvelope_type\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x06 \x01(\t\x12\x12\n\nrequest_id\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\r\n\x05\x65rror\x18\t \x01(\t\x12\x12\n\nerror_code\x18\n \x01(\t\x12\x13\n\x0b\x66rom_client\x18\x0b \x01(\t\x12\x11\n\tto_client\x18\x0c \x01(\t\x12(\n\x07payload\x18\x14 \x01(\x0b\x32\x17.google.protobuf.Struct\x12%\n\x04\x61rgs\x18\x15 \x01(\x0b\x32\x17.google.protobuf.Struct\x12)\n\x08metadata\x18\x16 \x01(\x0b\x32\x17.google.protobuf.Structb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bus_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSPAYLOAD']._serialized_start=68
  _globals['_BUSPAYLOAD']._serialized_end=426
# @@protoc_insertion_point(module_scope)
