# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envelope.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65nvelope.proto\x12\x08\x61rqon.v1\"\xd3\x02\n\x08\x45nvelope\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x10\n\x08twist_id\x18\x05 \x01(\t\x12\x30\n\x07headers\x18\x06 \x03(\x0b\x32\x1f.arqon.v1.Envelope.HeadersEntry\x12\x11\n\tsignature\x18\n \x01(\x0c\x12 \n\x03\x63md\x18\x14 \x01(\x0b\x32\x11.arqon.v1.CommandH\x00\x12 \n\x05\x65vent\x18\x15 \x01(\x0b\x32\x0f.arqon.v1.EventH\x00\x12(\n\x06signal\x18\x16 \x01(\x0b\x32\x16.arqon.v1.SystemSignalH\x00\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\t\n\x07payload\"%\n\x07\x43ommand\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"#\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x83\x01\n\x0cSystemSignal\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.arqon.v1.SystemSignal.SignalType\x12\x0e\n\x06reason\x18\x02 \x01(\t\"2\n\nSignalType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nDISCONNECT\x10\x01\x12\x07\n\x03\x42\x41N\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE_HEADERSENTRY']._loaded_options = None
  _globals['_ENVELOPE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_ENVELOPE']._serialized_start=29
  _globals['_ENVELOPE']._serialized_end=368
  _globals['_ENVELOPE_HEADERSENTRY']._serialized_start=311
  _globals['_ENVELOPE_HEADERSENTRY']._serialized_end=357
  _globals['_COMMAND']._serialized_start=370
  _globals['_COMMAND']._serialized_end=407
  _globals['_EVENT']._serialized_start=409
  _globals['_EVENT']._serialized_end=444
  _globals['_SYSTEMSIGNAL']._serialized_start=447
  _globals['_SYSTEMSIGNAL']._serialized_end=578
  _globals['_SYSTEMSIGNAL_SIGNALTYPE']._serialized_start=528
  _globals['_SYSTEMSIGNAL_SIGNALTYPE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
